# Site settings
title: JXH Blog                          #博客的标题
SEOTitle: 江小黑的博客 | JXH Blog         #显示在浏览器上搜索的时候的标题
header-img: img/post-bg-desk.jpg        
email: 765802997@qq.com
description: "做一只快快乐乐的小黑仔."    #网站介绍
keyword: "JXH, JXH Blog, 江小黑的博客, jxh, 江小黑, 前端"   #关键词
url: "http://zyjxh.github.io"          # 博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zyjxh/zyjxh.github.io.git" # you code repository

# Sidebar settings  
sidebar: true                           # 是否开启侧边栏
sidebar-about-description: "欢迎来到我的世界"   
sidebar-avatar: /img/about-JXH-gentle.jpg      # 个人头像


 
# SNS settings    #社交账号
RSS: false
# weibo_username:     我
zhihu_username:     是
github_username:    江
facebook_username:  小
jianshu_username:   黑
#twitter_username:   zyjxh




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: zyjxh

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: zyjxh.github.io    #仓库名称
  owner: zyjxh    #github用户名
  admin: zyjxh
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 

# Google Analytics
ga_track_id: ''            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "WY",
    #     href: "http://zhengwuyang.com"
    # },{
    #     title: "简书·BY",
    #     href: "http://www.jianshu.com/u/e71990ada2fd"
    # },{
    #     title: "Apple",
    #     href: "https://apple.com"
    # },{
    #     title: "Apple Developer",
    #     href: "https://developer.apple.com/"
    # }
]
